clc

fprintf("Welcome to my MATLAB implementation of Sudoku!\n\n")
pause(2);
fprintf("Use these commands to navigate around:\n\n" + ...
    "help - list the available commands\n" + ...
    "generate <easy/medium/hard> - generate a Sudoku puzzle of the specified difficulty\n" + ...
    "fill <row,column,value> - fill the given cell with the provided value\n" + ...
    "clue - reveal the correct value of a cell in the current puzzle (with justification if possible)\n\n" + ...
    "verify - check whether the puzzle is still solvable (to check for any wrong fills)\n" + ...
    "solve - solve the entirety of the current puzzle\n" + ...
    "undo - undo the last fill\n\n" + ...
    "save - outputs the current Sudoku puzzle state as a string that can be copied and pasted\n" + ...
    "load <string> - loads a Sudoku puzzle from a copied string\n" + ...
    "exit - exit the game\n\n")
handle_input(input("Your Choice: ", "s"))

% use rng somehow
% have different ways to input (individual number vs whole matrix)
% backtracking solver (never guess a value which already exists in the same row/column/block)

default_game_matrix = zeros(9,9);

default_game_matrix = generate_matrix();

editable_game_matrix = default_game_matrix;

display_matrix(default_game_matrix);

default_game_matrix(1,2) = 3;