% Function that prints the given Sudoku puzzle (matrix) formatted, to the
% command window

function [] = print_help()
    fprintf("help - list the available commands\n" + ...
    "explain - explains how to solve Sudoku puzzles\n" + ...
    "puzzle (easy/hard) - select a random puzzle from a set list to play\n" + ...
    "gen_puzzle (very_easy/easy/medium) - generate a Sudoku puzzle of the specified difficulty\n" + ...
    "display - display the current puzzle\n" + ...
    "fill <row,column,value> - fill the given cell with the provided value\n" + ...
    "clue - reveal the correct value of a cell in the current puzzle (with justification if possible)\n\n" + ...
    "verify - check whether the puzzle is still solvable (to check for any wrong fills)\n" + ...
    "solve - solve the entirety of the current puzzle\n" + ...
    "undo - undo the last fill\n\n" + ...
    "save - outputs the current Sudoku puzzle state as a string that can be copied and pasted\n" + ...
    "load <string> - loads a Sudoku puzzle from a copied string\n" + ...
    "extras (imshow/imsave/plot/randword/surround) - graphically display or save the puzzle, plot the pizzle in a figure, print a random word from dict.txt, surround a random integer with another random integer\n" + ...
    "exit - exit the game\n\n");
end