% This function prints the available user-input commands.

function [] = print_help()
    fprintf("help - list the available commands\n" + ...
    "explain - explains how to solve Sudoku puzzles\n" + ...
    "puzzle (easy/hard) - select a random puzzle from a set list to play\n" + ...
    "gen_puzzle (easy/medium) - generate a Sudoku puzzle of the specified difficulty\n" + ...
    "display - display the current puzzle\n" + ...
    "fill <row,column,value> - fill the given cell with the provided value\n" + ...
    "clue - attempt to reveal the correct value of a cell in the current puzzle\n\n" + ...
    "verify - attempt to check whether the puzzle is still solvable (to check for any wrong fills)\n" + ...
    "solve - attempt to solve the entirety of the current puzzle\n" + ...
    "undo - undo the last fill\n\n" + ...
    "save - outputs the current Sudoku puzzle state as a string that can be copied and pasted\n" + ...
    "load <string> - loads a Sudoku puzzle from a copied string\n" + ...
    "extras (plot/imshow/imwrite/randword) - plot the current puzzle on an plane\n" + ...
    "    by using a figure, display or save the puzzle as a grayscale image,\n" + ...
    "    or print a random word relating to a Sudoku-solving technique from a txt file\n" + ...
    "exit - exit the game\n\n");
end